# Generated by Django 3.2.14 on 2022-08-13 11:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatmedical',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
