# Generated by Django 3.2.15 on 2022-08-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_certificatmedical_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/%d/')),
            ],
        ),
    ]
