# Generated by Django 3.2.15 on 2022-08-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_pdfstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfstore',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
