# Generated by Django 3.2.15 on 2022-08-16 13:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_auto_20220813_1248'),
        ('consultation', '0004_alter_pdfstore_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreOrientation',
            fields=[
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='first_app.consultation')),
                ('text', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
