# Generated by Django 3.2.15 on 2022-08-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_lettreorientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfLettreStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/lettre/')),
            ],
        ),
        migrations.AlterField(
            model_name='pdfstore',
            name='file',
            field=models.FileField(upload_to='pdfs/cetificat/'),
        ),
    ]
