# Generated by Django 3.2.15 on 2022-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20220816_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfArretTravailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/arret_travail/')),
            ],
        ),
    ]
