# Generated by Django 3.2.15 on 2022-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_pdfbilanstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfOrdonnanceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/ordonnance/')),
            ],
        ),
    ]
