# Generated by Django 3.2.15 on 2022-08-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_pdfordonnancestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
