# Generated by Django 3.2.15 on 2022-08-19 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_consultationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdocument',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
