# Generated by Django 3.2.15 on 2022-08-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_remove_medicament_updated'),
        ('consultation', '0014_consultationdocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdocument',
            name='consultation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='first_app.consultation'),
        ),
    ]
