# Generated by Django 3.2.15 on 2022-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_alter_consultationdocument_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
