# Generated by Django 3.2.15 on 2022-08-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_remove_medicament_updated'),
        ('consultation', '0016_alter_consultationdocument_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdocument',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='first_app.consultation'),
        ),
        migrations.AlterField(
            model_name='consultationdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
