# Generated by Django 3.2.15 on 2022-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_auto_20220820_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdocument',
            name='file',
            field=models.FileField(upload_to='consultation/documents/'),
        ),
    ]
