# Generated by Django 3.2.15 on 2022-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_alter_consultationdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdocument',
            name='file',
            field=models.FileField(upload_to='consultation/documents/%Y/'),
        ),
    ]
