# Generated by Django 3.2.15 on 2022-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0019_alter_consultationdocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nommedicament',
            options={'ordering': ('nom',), 'verbose_name': 'Médicament', 'verbose_name_plural': 'Médicaments'},
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de médicament'),
        ),
    ]
