# Generated by Django 3.2.15 on 2022-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0020_auto_20220825_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Examen clinique')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen clinique',
                'verbose_name_plural': 'Examens cliniques',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='MotifConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Motif de consultation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motif de consultation',
                'verbose_name_plural': 'Motif de consultation',
                'ordering': ('nom',),
            },
        ),
    ]
