# Generated by Django 3.2.15 on 2022-08-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_auto_20220825_1659'),
        ('consultation', '0021_examenclinique_motifconsultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attentes', to='first_app.patient')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
