# Generated by Django 3.2.15 on 2022-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0022_salleattente'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('specialite', models.CharField(max_length=300)),
                ('ecole', models.CharField(max_length=300)),
                ('ar_nom', models.CharField(max_length=300)),
                ('ar_specialite', models.CharField(max_length=300)),
                ('ar_ecole', models.CharField(max_length=300)),
                ('gsm', models.CharField(max_length=20)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField()),
            ],
        ),
    ]
