# Generated by Django 3.2.15 on 2022-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0026_alter_infodoctor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodoctor',
            name='ville',
            field=models.CharField(default='casablanca', max_length=300),
            preserve_default=False,
        ),
    ]
