# Generated by Django 3.2.15 on 2022-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0028_delegnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='nommedicament',
            name='Prix',
            field=models.CharField(default=12, max_length=100, verbose_name='Prix br'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='code',
            field=models.CharField(default=12, max_length=500, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='dci1',
            field=models.CharField(default=12, max_length=500, verbose_name='DCI1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='dosage',
            field=models.CharField(default=12, max_length=200, verbose_name='Dosage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='form',
            field=models.CharField(default=12, max_length=200, verbose_name='Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='ph',
            field=models.CharField(default=12, max_length=100, verbose_name='PH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='ppv',
            field=models.CharField(default=12, max_length=100, verbose_name='PPV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='presentation',
            field=models.CharField(default=12, max_length=200, verbose_name='Présentation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='nom',
            field=models.CharField(max_length=500, verbose_name='Nom de médicament'),
        ),
    ]
