# Generated by Django 3.2.15 on 2022-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0029_auto_20220829_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nommedicament',
            name='form',
            field=models.CharField(max_length=200, verbose_name='Forme'),
        ),
    ]
