# Generated by Django 3.2.15 on 2022-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0030_alter_nommedicament_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='nommedicament',
            name='princeps_generique',
            field=models.CharField(blank=True, max_length=100, verbose_name='Princeps generique'),
        ),
        migrations.AddField(
            model_name='nommedicament',
            name='taux_remboursement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Taux de remboursement'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='Prix',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix brut'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='dci1',
            field=models.CharField(blank=True, max_length=500, verbose_name='DCI1'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='form',
            field=models.CharField(blank=True, max_length=200, verbose_name='Forme'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='PH'),
        ),
        migrations.AlterField(
            model_name='nommedicament',
            name='ppv',
            field=models.FloatField(blank=True, null=True, verbose_name='PPV'),
        ),
    ]
