# Generated by Django 3.2.15 on 2022-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0031_auto_20220829_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nommedicament',
            name='code',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
