# Generated by Django 3.2.15 on 2022-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0032_alter_nommedicament_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nommedicament',
            name='dosage',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dosage'),
        ),
    ]
