# Generated by Django 3.2.15 on 2022-08-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0033_alter_nommedicament_dosage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500, verbose_name='Posologie')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posologie',
                'verbose_name_plural': 'Posologies',
                'ordering': ('nom',),
            },
        ),
    ]
