# Generated by Django 3.2.15 on 2022-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0035_infodoctor_logo_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500, verbose_name='Quantité')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quantité',
                'verbose_name_plural': 'Quantités',
                'ordering': ('nom',),
            },
        ),
    ]
