# Generated by Django 3.2.15 on 2022-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0036_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
