# Generated by Django 3.2.18 on 2023-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0037_payment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salleattente',
            name='motif',
            field=models.CharField(choices=[('NC', 'NC'), ('AC', 'AC'), ('CTR', 'CTR')], default='NC', max_length=10),
        ),
    ]
