# Generated by Django 3.2.18 on 2023-03-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0038_salleattente_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationdocument',
            name='description',
        ),
        migrations.AlterField(
            model_name='consultationdocument',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
