# Generated by Django 3.2.18 on 2023-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0039_auto_20230325_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salleattente',
            name='motif',
            field=models.CharField(choices=[('NC', 'NC'), ('CTR', 'CTR')], default='NC', max_length=10),
        ),
    ]
