# Generated by Django 3.2.18 on 2023-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0040_alter_salleattente_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodoctor',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='ar_ecole',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='ar_nom',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='ar_specialite',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='ecole',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='gsm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='logo',
            field=models.ImageField(blank=True, default='logo_doctor.jpg', upload_to='logo_clinic/'),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='logo_center',
            field=models.ImageField(blank=True, default='logo_doctor.jpg', upload_to='logo_clinic/'),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='nom',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='specialite',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='infodoctor',
            name='ville',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
