# Generated by Django 3.2.18 on 2023-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0041_auto_20230404_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salleattente',
            name='motif',
            field=models.CharField(choices=[('NC', 'NC'), ('AC', 'AC'), ('CTR', 'CTR')], default='NC', max_length=10),
        ),
    ]
