# Generated by Django 3.2.14 on 2022-07-20 20:29

from django.db import migrations
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=first_app.models.LowerCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=first_app.models.LowerCharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name', 'year_of_birth', 'sexe')},
        ),
    ]
