# Generated by Django 3.2.14 on 2022-07-21 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20220720_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5, "Le nombre d'éléments par page doit être supérieur à 5")])),
            ],
        ),
    ]
