# Generated by Django 3.2.14 on 2022-07-21 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_itemnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnum',
            name='nums',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5, "Le nombre d'éléments par page doit être supérieur à 5")]),
        ),
    ]
