# Generated by Django 3.2.14 on 2022-07-25 15:15

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_appointement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200)),
                ('diagnostique', models.TextField()),
                ('examen', models.TextField()),
                ('poids_kg', models.IntegerField(blank=True, null=True, validators=[first_app.models.validate_poids])),
                ('taille_cm', models.IntegerField(blank=True, null=True, validators=[first_app.models.validate_taille])),
                ('temperature_degC', models.IntegerField(blank=True, null=True, validators=[first_app.models.validate_temperature])),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True, validators=[first_app.models.validate_frequence])),
                ('pression_arterielle', models.IntegerField(blank=True, null=True, validators=[first_app.models.validate_pression])),
                ('observation', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='first_app.patient')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
