# Generated by Django 3.2.14 on 2022-07-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnostique',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='examen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
