# Generated by Django 3.2.14 on 2022-07-31 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_medicament'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='first_app.consultation')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
