# Generated by Django 3.2.14 on 2022-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_patient_cnie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cnie',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
