# Generated by Django 3.2.14 on 2022-08-07 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
