# Generated by Django 3.2.14 on 2022-08-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_analyse_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyse',
            options={'ordering': ('-date',)},
        ),
    ]
