# Generated by Django 3.2.15 on 2022-08-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_auto_20220813_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrettravail',
            name='id',
        ),
        migrations.AddField(
            model_name='arrettravail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arrettravail',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='first_app.consultation'),
        ),
    ]
