# Generated by Django 3.2.15 on 2022-08-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20220817_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='updated',
        ),
    ]
