# Generated by Django 3.2.15 on 2022-08-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_remove_medicament_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointement',
            options={'ordering': ('date', 'hour')},
        ),
    ]
