# Generated by Django 3.2.15 on 2022-08-25 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0025_alter_appointement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': "Photos d'utilisateurs", 'verbose_name_plural': "Photos d'utilisateurs"},
        ),
        migrations.AlterModelOptions(
            name='testname',
            options={'ordering': ('-created',), 'verbose_name': 'Bilan', 'verbose_name_plural': 'Bilans'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='imc',
            field=models.FloatField(blank=True, null=True, validators=[first_app.models.validate_imc]),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sao2',
            field=models.IntegerField(blank=True, null=True, validators=[first_app.models.validate_sao2]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='testname',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='testname',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de bilan'),
        ),
    ]
