# Generated by Django 3.2.15 on 2022-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_auto_20220825_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='antecedant',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
