# Generated by Django 3.2.15 on 2022-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_auto_20220825_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='antecedant',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.TextField(blank=True),
        ),
    ]
