# Generated by Django 3.2.15 on 2022-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_auto_20220825_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='qsp',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='posologie',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
