# Generated by Django 3.2.15 on 2022-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0029_auto_20220829_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nbr_unite',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
