# Generated by Django 3.2.15 on 2022-08-30 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_alter_medicament_nbr_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^0\\d{9}', 'Le numéro de téléphone doit commencer par 0 et avoir une longueur de 10.')]),
        ),
    ]
