# Generated by Django 3.2.15 on 2022-08-30 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0032_itemnum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemnums', to=settings.AUTH_USER_MODEL),
        ),
    ]
