# Generated by Django 3.2.15 on 2022-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_alter_itemnum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nbr_unite',
            field=models.CharField(blank=True, default='aa', max_length=500),
            preserve_default=False,
        ),
    ]
