# Generated by Django 3.2.18 on 2023-03-28 12:48

from django.db import migrations, models
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_alter_patient_mutuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='temperature_degC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[first_app.models.validate_temperature]),
        ),
    ]
