# Generated by Django 3.2.18 on 2023-03-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0038_consultation_pression_arterielle'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ct',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hdl',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ldl',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tg',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
