# Generated by Django 3.2.18 on 2023-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0039_auto_20230331_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
