# Generated by Django 3.2.18 on 2023-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0040_patient_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='g',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
